pipeline {
       agent any
       
          stages {
                    stage('checkout') {
                                  steps {
                                                  git branch: 'main', url: 'https://github.com/anuroopps/DO400-apps'
                                  }
                    }
                          stage('test') {
                                        steps {
                                                        sh './story-count/test-wc.sh ./story-count/random.txt'
                                        }
                          }
          }
}
    
